// <auto-generated />
namespace MVCEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InsertingGenreintoTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertingGenreintoTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202004191202034_InsertingGenreintoTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
